apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: a-silence-of-three-parts
spec:
  deployed: true
  powDifficultySeconds: 5
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/idekctf-374221/a-silence-of-three-parts-healthcheck:92b08f2cb1ad5a57cc6165974766c167be4c9685831067e037c80bb5df07bf3e
  image: us.gcr.io/idekctf-374221/a-silence-of-three-parts-challenge:5319e3e63e7f4e778a73d0f2743ad72f9d1640b982533e38b9d97baf6c3784fc
