name: crator
author: __jw
public: true
flag: idek{1m4g1n3_n0t_h4v1ng_pr0p3r_s4ndb0x1ng}
description: I made a new website to compete against my friends to see who could write faster code. Unfortunately, I don't actually know how to write that much code. Don't tell them, but ChatGPT wrote this entire website for me. Can you solve the problems for me?
instancer: true