name: memoryfs
author: __jw
public: true
flag: "idek{sh311_r3wr1t3_sh3n4n1g4ns}"
description: |-
  Are you sick and tired of law enforcement busting down your door, stealing your hard drives, and then finding all your pirated movies? Well, fret no more, because with MemoryFS, once those goons unplug your computer, your files are wiped!
