name: NM~~PZ~~ - medium
author: jazzzooo
flag: idek{idekctf_infra_is_hosted_in_salekhard_a07ca573}
public: true
description: |
  Some harder strategies are required for this one.

  [http://nmpz.chal.idek.team:1337/](http://nmpz.chal.idek.team:1337/)