name: nlibs baby
author: JoshL
flag: idek{now_do_this_9999_more_times}
public: true
attachments:
  - baby.tar.gz
description: |-
  In celebration on qualifying for DEFCON CTF Finals, I have prepared a throwback challenge!
  
  Note: There's a $50 USD author bounty on this challenge first blood.