name: NM~~PZ~~ - hard
author: jazzzooo
public: true
flag: idek{next_year_only_indoor_photospheres_49c8e584}
description: |
  The best part of making this is not needing to solve it.

  [http://nmpz.chal.idek.team:1337/](http://nmpz.chal.idek.team:1337/)


  **Hint for NMPZ - hard butterfly**: It is located in Lithuania
