name: nlibs
author: JoshL
flag: idek{when_will_we_get_n^2_cuts?}
public: true
attachments:
  - nlibs.tar.gz
description: |-
  What's not to love about a DEFCON style challenge than a two part rev challenge?
