name: The Moon
author: Trixter & Ling
public: true
flag: idek{th3_m0on_h4t3s_b31ng_t4mp3r3d_w1th_c3aec291}
description: |-
  Someone kept talking about something how they used the moon to hide their flag but I'm not sure what that was all about...
