name: Minecraft - HACKED
author: JoshL
public: true
flag: idekCTF{storage_tech_is_my_passion_c1bdf8b2}
description: You might remember the [cat coordinate
  exploit](https://www.youtube.com/watch?v=TAUrzkOYLUk) used to find
  LiveOverflow. Well, pumpkin steve has captured LiveOverflow, and it is your job to find LiveOverflow again. But this time
  he left something else behind...


  **PLEASE TEST YOUR SOLVE LOCALLY BEFORE STARTING AN INSTANCE**


  After starting the instancer, run `socat tcp-listen:25565,fork,reuseaddr openssl:<REMOTE_HOST_HERE>:1337` and join the server on `localhost:25565`
  
instancer: true