name: Game
author: Elvis
public: true
flag: idek{Y0U_MuST_BE_n3ItheR_a_prO_PlaY3R_N0r_@_cHeATer}
description: |-
  I have pulled a game from https://github.com/shlomnissan/trex-runner and modified it to add a reward for players who achieve a high enough score. Check it out!