name: srcdoc-memos-revenge
author: icesfont
public: true
flag: idek{why._why,_7cfa90ee52}
description: |-
  This is a revenge challenge for srcdoc-memos

  Note: Exploits should target to http://localhost:1337

  hint 1: policy containers in chromium

  hint 2: what can you do with a srcdoc without csp, even if you don't have scripting?
instancer: true
instancer_id: srcdoc-revenge