name: Hello
author: Abdelhameed Ghazy
public: true
flag: idek{Ghazy_N3gm_Elbalad}
description: |-
  Just to warm you up for the next Fight :"D

  Note: the admin bot is not on the same machine as the challenge itself and the *.chal.idek.team:1337 URL should be used for the admin bot URL
admin_bot: true
http: true