version: "3.8"
name: "srcdoc-memos"

services:
  web:
    build: web
    ports:
      - "1337:1337"
    restart: always

  bot:
    build: bot
    environment:
      SITE: http://web:1337  # this will point to the public instance on remote
    ports:
      - "3000:8080"

