name: irrandomcible
author: A~Z
public: true
flag: idek{5um_0f_1rr3p_15_d14g0n4l}
description: |-
  **And in the left corner! Beer in hand, degen anime in mind! You all recognize him, the drunk cryptoman!! SOOOOOOOOOON HAAAAAARRIIIIIIII**

  While attempting to become as good as my idol Haari-sama of the Soon clan, I got drunk and randomized the flag. Please help.
