name: Busy ~~Gambler~~ Pwner
author: Zerotistic
public: true
flag: idek{automation_is_fun_but_it_could_be_funnier_by_being_harder}
description: |-
  So huh I spent the whole month gambling... And haven't done a single work!! I have a few binaries I really need to exploit, please help me !! :(
  *Note: please check `template.py` as it contains useful information*