apiVersion: "klodd.tjcsec.club/v1"
kind: Challenge
metadata:
  name: srcdoc-revenge
spec:
  name: srcdoc memos revenge
  timeout: 1800000 # 30min
  pods:
    - name: app
      egress: true
      ports:
        - port: 1337
      spec:
        containers:
          - name: main
            image: gcr.io/idekctf-374221/srcdoc-memos-revenge
            resources:
              requests:
                memory: 200Mi
                cpu: 200m
              limits:
                memory: 500Mi
                cpu: 500m
        automountServiceAccountToken: false
  expose:
    kind: http
    pod: app
    port: 1337
