name: Golden Ticket
author: Giapppp
public: true
flag: idek{charles_and_the_chocolate_factory!!!}
description: Can you help Charles - who doesn't have any knowledge about cryptography, get the golden ticket and have a trip to Willy Wonka's factory ?