name: Ribasu Metronome
author: Rythm
public: true
flag: idekCTF{1_l0v3_k4t0u_but_1_4ls0_l0v3_ut4h4_1s_th1s_th3_m3tr0n0m3}
description: |-
  Utaha made a flag checker that works most of the time. Sometimes it's hard to make up your mind.